# Impostazioni generali
general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true   # Evita di mostrare l'errore se premi invio a vuoto
}

# Sfondo (puoi usare un'immagine o catturare lo screenshot attuale)
background {
    monitor =
    path = screenshot          # Prende uno screenshot corrente e lo usa come sfondo
    # path = /home/tuoutente/Immagini/wallpaper.png # Oppure usa un percorso assoluto
    
    color = rgba(25, 20, 20, 1.0)

    # Effetto sfocatura (Blur)
    blur_passes = 3            # Maggiore è il numero, più è sfocato
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

# Orologio (Label)
label {
    monitor =
    #text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = JetBrainsMono Nerd Font # Assicurati che il font sia installato

    position = center
    halign = center
    valign = center
}

# Input Field (Scatola Password)
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # Scala della dimensione dei pallini (0.2 - 0.8)
    dots_spacing = 0.15 # Scala dello spazio tra i pallini (0.0 - 1.0)
    dots_center = true
    
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    
    fade_on_empty = false
    placeholder_text = <i>Inserisci la password...</i> # Supporta la formattazione pango
    
    hide_input = false

    position = 0, -20
    halign = center
    valign = center
}

